FROM rust:1.88-slim-bookworm AS tun2proxy-build

ENV GIT_HASH=crates-io

ARG TUN2PROXY_VERSION=0.7.21
RUN cargo install --locked --version "${TUN2PROXY_VERSION}" --bin tun2proxy-bin tun2proxy

# harness-hat base — Ubuntu 24.04 LTS (Noble Numbat)
#
# Build (from repo root):
#   docker build -t harness-hat-base:local -f docker/harness-hat-base.dockerfile .
#
# Run command is generated by the harness-hat TUI for your project.
#
# ── Network filtering and CA trust ───────────────────────────────────────────
# harness-hat routes container traffic through its MITM proxy and injects CA
# bundle paths via environment variables at run time. The bundle combines system
# public roots with the harness-hat CA so TLS passthrough and MITM traffic both
# validate. Most runtimes are covered automatically:
#
#   CODEX_CA_CERTIFICATE / SSL_CERT_FILE / CURL_CA_BUNDLE
#                                             OpenAI Codex, OpenSSL, curl, Go, Ruby, PHP
#   NODE_EXTRA_CA_CERTS / DENO_CERT         — Node.js, npm, yarn, bun, Deno
#   REQUESTS_CA_BUNDLE / AWS_CA_BUNDLE      — Python (requests/httpx/pip), AWS SDK
#   GIT_SSL_CAINFO                          — git over HTTPS
#   GRPC_DEFAULT_SSL_ROOTS_FILE_PATH        — gRPC (all language runtimes)
#
# harness-hat-init.sh also runs update-ca-certificates (when root) to update the system
# store, which covers .NET / C# (HttpClient, RestSharp, etc.).  Omit --user
# from your docker run flags to allow this; with --user 1000:1000 the system
# store update is skipped (env-var-based runtimes still work fine).
#
# Java / JVM (OkHttp, Apache HttpClient, java.net.http, Ktor, etc.) maintains
# its own keystore and ignores the system store and env vars.  The CA cert is
# only bind-mounted at run time, so keytool must run at container start, not
# during the image build.  Extend harness-hat-init.sh in your downstream Dockerfile:
#
#   keytool -importcert -noprompt -alias harness-hat -cacerts \
#     -storepass changeit \
#     -file /usr/local/share/ca-certificates/harness-hat-ca.crt 2>/dev/null || true
#
# Rust / rustls + webpki-roots: uses a compiled-in Mozilla bundle and ignores
# all env vars and the system store.  To intercept traffic from such binaries,
# either patch the application to load extra roots at startup, or rebuild with
# the native-tls / openssl-sys backend so SSL_CERT_FILE is honoured.

FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
ARG UBUNTU_ARCHIVE_MIRRORS="http://archive.ubuntu.com/ubuntu/ http://us.archive.ubuntu.com/ubuntu/ http://mirrors.edge.kernel.org/ubuntu/ http://mirror.us.leaseweb.net/ubuntu/"
ARG UBUNTU_PORTS_MIRRORS="http://ports.ubuntu.com/ubuntu-ports/ http://mirror.us.leaseweb.net/ubuntu-ports/ http://mirrors.edge.kernel.org/ubuntu-ports/"

# Ubuntu archive and ports mirrors can be unreachable from some networks. Try a
# short list before the first package install and leave apt pointed at the first
# mirror that works.
RUN set -eu; \
    sources=/etc/apt/sources.list.d/ubuntu.sources; \
    upstream=; \
    mirrors=; \
    if grep -q 'http://ports.ubuntu.com/ubuntu-ports/' "$sources"; then \
      upstream='http://ports.ubuntu.com/ubuntu-ports/'; \
      mirrors="$UBUNTU_PORTS_MIRRORS"; \
    elif grep -q 'http://archive.ubuntu.com/ubuntu/' "$sources"; then \
      upstream='http://archive.ubuntu.com/ubuntu/'; \
      mirrors="$UBUNTU_ARCHIVE_MIRRORS"; \
    fi; \
    if [ -n "$upstream" ]; then \
      cp "$sources" /tmp/ubuntu.sources.orig; \
      selected_mirror=; \
      for mirror in $mirrors; do \
        sed \
          -e "s#${upstream}#${mirror}#g" \
          -e "s#http://security.ubuntu.com/ubuntu/#${mirror}#g" \
          /tmp/ubuntu.sources.orig > "$sources"; \
        rm -rf /var/lib/apt/lists/*; \
        if apt-get update -o APT::Update::Error-Mode=any; then \
          selected_mirror="$mirror"; \
          break; \
        fi; \
      done; \
      if [ -z "$selected_mirror" ]; then \
        cp /tmp/ubuntu.sources.orig "$sources"; \
        echo "No Ubuntu mirror worked from configured mirror list" >&2; \
        exit 1; \
      fi; \
      echo "Using Ubuntu mirror: $selected_mirror"; \
    fi

RUN apt-get update -o APT::Update::Error-Mode=any && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      gnupg \
      nano \
      git \
      python3 \
      python3-pip \
      python3-venv \
      unzip \
      bubblewrap \
      build-essential \
      iproute2 \
      iptables \
      gosu \
    && rm -rf /var/lib/apt/lists/*

# Install a current Node runtime for agent CLIs (Gemini CLI requires Node 20+).
# The NodeSource `nodejs` package already carries npm, and Ubuntu's `npm`
# package conflicts with it.
RUN set -eu; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
      | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" \
      > /etc/apt/sources.list.d/nodesource.list; \
    apt-get update -o APT::Update::Error-Mode=any && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/hostdo.py /usr/local/bin/hostdo
RUN chmod 755 /usr/local/bin/hostdo
COPY scripts/agentctl.py /usr/local/bin/agentctl
RUN chmod 755 /usr/local/bin/agentctl
COPY scripts/killme.py /usr/local/bin/killme
RUN chmod 755 /usr/local/bin/killme
COPY --from=tun2proxy-build /usr/local/cargo/bin/tun2proxy-bin /usr/local/bin/tun2proxy-bin

# Trusts the harness-hat MITM CA cert bind-mounted at run time (root only).
RUN cat > /usr/local/bin/harness-hat-init.sh << 'SCRIPT'
#!/bin/sh
set -e
HH_CERT="/usr/local/share/ca-certificates/harness-hat-ca.crt"
HH_SYSTEM_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
HH_COMBINED_BUNDLE="/tmp/harness-hat-ca-bundle.crt"
if [ -f "$HH_CERT" ] && [ "$(id -u)" = "0" ]; then
    update-ca-certificates 2>/dev/null || true
fi
if [ -f "$HH_CERT" ]; then
    if [ -f "$HH_SYSTEM_BUNDLE" ]; then
        cat "$HH_SYSTEM_BUNDLE" "$HH_CERT" > "$HH_COMBINED_BUNDLE" 2>/dev/null || true
    else
        cp "$HH_CERT" "$HH_COMBINED_BUNDLE" 2>/dev/null || true
    fi
    chmod 0644 "$HH_COMBINED_BUNDLE" 2>/dev/null || true
fi

# Subagents receive read-only snapshots of agent auth/config state instead of
# bind-mounted writable home directories. Copy those snapshots into the fresh
# container filesystem before dropping privileges so each subagent can write its
# own runtime state without contending with siblings or the primary agent.
HH_AGENT_CONFIG_MANIFEST="${HARNESS_HAT_AGENT_CONFIG_SNAPSHOT:-}"
if [ -n "$HH_AGENT_CONFIG_MANIFEST" ] && [ -f "$HH_AGENT_CONFIG_MANIFEST" ]; then
    tab="$(printf '\t')"
    while IFS="$tab" read -r src_rel dest_path; do
        [ -n "$src_rel" ] || continue
        [ -n "$dest_path" ] || continue
        src_path="/tmp/harness-hat-agent-config/$src_rel"
        [ -e "$src_path" ] || continue
        dest_parent="$(dirname "$dest_path")"
        mkdir -p "$dest_parent" 2>/dev/null || true
        rm -rf "$dest_path" 2>/dev/null || true
        if [ -d "$src_path" ]; then
            mkdir -p "$dest_path" 2>/dev/null || true
            cp -a "$src_path"/. "$dest_path"/ 2>/dev/null || true
        else
            cp -a "$src_path" "$dest_path" 2>/dev/null || true
        fi
        chown -R 1000:1000 "$dest_path" 2>/dev/null || true
    done < "$HH_AGENT_CONFIG_MANIFEST"
fi

# Best-effort: ensure bind-mounted auth/session state under /home/ubuntu is
# readable by uid 1000 (common issue on macOS/Linux).
if [ "$(id -u)" = "0" ]; then
    if [ -f /home/ubuntu/.claude.json ]; then
        chown 1000:1000 /home/ubuntu/.claude.json 2>/dev/null || true
        chmod 600 /home/ubuntu/.claude.json 2>/dev/null || true
    fi
    if [ -d /home/ubuntu/.claude ]; then
        chown -R 1000:1000 /home/ubuntu/.claude 2>/dev/null || true
        chmod 700 /home/ubuntu/.claude 2>/dev/null || true
        chmod -R u+rwX /home/ubuntu/.claude 2>/dev/null || true
    fi
fi

# Copy staged Claude credentials into place.  harness-hat mounts the host
# keychain credential at a staging path to avoid nested bind-mount conflicts.
HH_STAGED_CREDS="/tmp/.harness-hat-claude-credentials.json"
if [ -f "$HH_STAGED_CREDS" ]; then
    CLAUDE_DIR="/home/ubuntu/.claude"
    mkdir -p "$CLAUDE_DIR" 2>/dev/null || true
    cp "$HH_STAGED_CREDS" "$CLAUDE_DIR/.credentials.json" 2>/dev/null || true
    chown 1000:1000 "$CLAUDE_DIR/.credentials.json" 2>/dev/null || true
    chmod 600 "$CLAUDE_DIR/.credentials.json" 2>/dev/null || true
fi

start_localhost_forwards() {
    HH_LOCALHOST_FORWARDS="${HARNESS_HAT_LOCALHOST_FORWARDS:-}"
    [ -n "$HH_LOCALHOST_FORWARDS" ] || return 0
    HH_LOCALHOST_FORWARD_HOST="${HARNESS_HAT_LOCALHOST_FORWARD_HOST:-host.docker.internal}"
    HH_LOCALHOST_FORWARD_TARGET="$(getent ahostsv4 "$HH_LOCALHOST_FORWARD_HOST" 2>/dev/null | awk '{print $1; exit}')"
    [ -n "$HH_LOCALHOST_FORWARD_TARGET" ] || HH_LOCALHOST_FORWARD_TARGET="$HH_LOCALHOST_FORWARD_HOST"
    python3 - "$HH_LOCALHOST_FORWARDS" "$HH_LOCALHOST_FORWARD_TARGET" <<'PY' &
import select
import socket
import sys
import threading

spec_arg = sys.argv[1]
target_host = sys.argv[2]


def parse_port(value):
    try:
        port = int(value)
    except ValueError as exc:
        raise ValueError(f"invalid port {value!r}") from exc
    if port < 1 or port > 65535:
        raise ValueError(f"port out of range: {port}")
    return port


forwards = []
for raw in spec_arg.split(","):
    raw = raw.strip()
    if not raw:
        continue
    if ":" in raw:
        container_port_raw, host_port_raw = raw.split(":", 1)
    else:
        container_port_raw = host_port_raw = raw
    forwards.append((parse_port(container_port_raw), parse_port(host_port_raw)))

if not forwards:
    sys.exit(0)


def relay(client, host_port):
    upstream = None
    try:
        upstream = socket.create_connection((target_host, host_port), timeout=10)
        client.setblocking(False)
        upstream.setblocking(False)
        sockets = [client, upstream]
        while True:
            readable, _, _ = select.select(sockets, [], [], 60)
            for sock in readable:
                data = sock.recv(65536)
                if not data:
                    return
                (upstream if sock is client else client).sendall(data)
    except Exception as exc:
        print(f"harness-hat: localhost forward connection failed: {exc}", file=sys.stderr)
    finally:
        for sock in (client, upstream):
            if sock is not None:
                try:
                    sock.close()
                except OSError:
                    pass


def listen(sock, bind_host, container_port, host_port):
    print(
        f"harness-hat: forwarding {bind_host}:{container_port} to {target_host}:{host_port}",
        file=sys.stderr,
        flush=True,
    )
    while True:
        client, _ = sock.accept()
        threading.Thread(target=relay, args=(client, host_port), daemon=True).start()


listeners = []
for container_port, host_port in forwards:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(("127.0.0.1", container_port))
    sock.listen(128)
    listeners.append((sock, "127.0.0.1", container_port, host_port))

    try:
        sock6 = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
        sock6.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock6.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
        sock6.bind(("::1", container_port))
        sock6.listen(128)
        listeners.append((sock6, "::1", container_port, host_port))
    except OSError as exc:
        print(
            f"harness-hat: warning: could not bind ::1:{container_port}: {exc}",
            file=sys.stderr,
            flush=True,
        )

for sock, bind_host, container_port, host_port in listeners:
    threading.Thread(
        target=listen,
        args=(sock, bind_host, container_port, host_port),
        daemon=True,
    ).start()

threading.Event().wait()
PY
    HH_LOCALHOST_FORWARD_PID=$!
    sleep 0.2
    if ! kill -0 "$HH_LOCALHOST_FORWARD_PID" 2>/dev/null; then
        echo "harness-hat: localhost forward setup failed" >&2
        exit 1
    fi
}

start_localhost_forwards

# Optional: strict network enforcement.
# TUN mode captures outbound TCP at the routing layer and forwards it through
# the harness-hat scoped HTTP proxy via tun2proxy.  This does not rely on the
# application honoring HTTP(S)_PROXY or ALL_PROXY.  UDP/QUIC are intentionally
# blocked; DNS to Docker's embedded resolver is allowed.
if [ "${HARNESS_HAT_STRICT_NETWORK:-0}" = "1" ]; then
    if [ "$(id -u)" != "0" ]; then
        echo "harness-hat: strict_network requires root" >&2
        exit 1
    fi
    if [ -z "${HARNESS_HAT_SCOPED_PROXY_ADDR:-}" ] || [ -z "${HARNESS_HAT_SCOPED_PROXY_AUTH:-}" ] || [ -z "${HARNESS_HAT_URL:-}" ]; then
        echo "harness-hat: strict_network missing HARNESS_HAT_SCOPED_PROXY_ADDR, HARNESS_HAT_SCOPED_PROXY_AUTH, or HARNESS_HAT_URL" >&2
        exit 1
    fi

    if [ ! -c /dev/net/tun ]; then
        echo "harness-hat: strict_network requires /dev/net/tun (Docker Desktop usually needs --privileged)" >&2
        exit 1
    fi

    # ── Pick the iptables binary that actually works ──────────────────────
    # Ubuntu 24.04 defaults to iptables-nft.  Docker Desktop's LinuxKit VM
    # may only support iptables-legacy.  Probe both and use the first that
    # succeeds at listing the filter/OUTPUT chain.
    IPT=""
    IP6T=""
    for candidate in iptables-legacy iptables; do
        if command -v "$candidate" >/dev/null 2>&1 \
           && "$candidate" -w -t filter -L OUTPUT -n >/dev/null 2>&1; then
            IPT="$candidate"
            break
        fi
    done
    for candidate in ip6tables-legacy ip6tables; do
        if command -v "$candidate" >/dev/null 2>&1 \
           && "$candidate" -w -t filter -L OUTPUT -n >/dev/null 2>&1; then
            IP6T="$candidate"
            break
        fi
    done
    if [ -z "$IPT" ]; then
        echo "harness-hat: strict_network requires a working iptables (tried iptables-legacy, iptables)" >&2
        exit 1
    fi

    proxy_host="${HARNESS_HAT_SCOPED_PROXY_ADDR%:*}"
    proxy_port="${HARNESS_HAT_SCOPED_PROXY_ADDR##*:}"
    proxy_conn_limit="${HARNESS_HAT_PROXY_CONN_LIMIT:-0}"
    case "$proxy_conn_limit" in
        ''|*[!0-9]*) proxy_conn_limit=0 ;;
    esac
    exec_hostport="$(printf '%s' "$HARNESS_HAT_URL" | sed -E 's#^[a-zA-Z]+://##')"
    exec_scheme="$(printf '%s' "$HARNESS_HAT_URL" | sed -E 's#^([a-zA-Z]+)://.*#\1#')"
    [ -n "$exec_scheme" ] || exec_scheme="http"
    exec_host="${exec_hostport%:*}"
    exec_port="${exec_hostport##*:}"

    proxy_ip="$(getent ahostsv4 "$proxy_host" 2>/dev/null | awk '{print $1; exit}')"
    exec_ip="$(getent ahostsv4 "$exec_host" 2>/dev/null | awk '{print $1; exit}')"
    forward_host="${HARNESS_HAT_LOCALHOST_FORWARD_HOST:-host.docker.internal}"
    forward_ip=""
    if [ -n "${HARNESS_HAT_LOCALHOST_FORWARDS:-}" ]; then
        forward_ip="$(getent ahostsv4 "$forward_host" 2>/dev/null | awk '{print $1; exit}')"
    fi
    if [ -z "$proxy_ip" ] || [ -z "$exec_ip" ]; then
        echo "harness-hat: strict_network failed to resolve proxy ($proxy_host) or exec ($exec_host) hosts" >&2
        exit 1
    fi
    if [ -n "${HARNESS_HAT_LOCALHOST_FORWARDS:-}" ] && [ -z "$forward_ip" ]; then
        echo "harness-hat: strict_network failed to resolve localhost forward host ($forward_host)" >&2
        exit 1
    fi

    # Keep hostdo control traffic on the direct exec-bridge path.
    # In strict mode with virtual DNS, hostnames can resolve to synthetic
    # 198.18.0.0/15 addresses; using the resolved bridge IP avoids that.
    export HARNESS_HAT_URL="${exec_scheme}://${exec_ip}:${exec_port}"

    echo "harness-hat: strict_network using $IPT; proxy=$proxy_ip:$proxy_port exec=$exec_ip:$exec_port proxy_conn_limit=$proxy_conn_limit" >&2
    # ── Layer 1: strict egress filter ────────────────────────────────────
    # Allow only: loopback, tun0 (captured traffic), established/related,
    # Docker DNS, proxy, exec, and configured localhost forwards. Traffic
    # written to tun0 is not raw egress;
    # tun2proxy consumes it in userspace and opens the real upstream sockets.
    # Anything escaping that path on a physical interface is rejected here.
    $IPT -w -t filter -N HH_EGRESS 2>/dev/null || $IPT -w -t filter -F HH_EGRESS
    $IPT -w -t filter -C OUTPUT -j HH_EGRESS 2>/dev/null || $IPT -w -t filter -I OUTPUT 1 -j HH_EGRESS
    $IPT -w -t filter -F HH_EGRESS
    $IPT -w -t filter -A HH_EGRESS -o lo -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -o tun0 -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p udp -d 127.0.0.11 --dport 53 -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p tcp -d 127.0.0.11 --dport 53 -j ACCEPT
    if [ "$proxy_conn_limit" -gt 0 ]; then
        if ! $IPT -w -t filter -A HH_EGRESS -p tcp -d "$proxy_ip" --dport "$proxy_port" \
            -m connlimit --connlimit-above "$proxy_conn_limit" --connlimit-mask 32 \
            -j REJECT 2>/dev/null; then
            echo "harness-hat: warning: iptables connlimit unavailable; scoped proxy socket cap disabled" >&2
        fi
    fi
    $IPT -w -t filter -A HH_EGRESS -p tcp -d "$proxy_ip" --dport "$proxy_port" -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p tcp -d "$exec_ip" --dport "$exec_port" -j ACCEPT
    if [ -n "${HARNESS_HAT_LOCALHOST_FORWARDS:-}" ]; then
        old_ifs="$IFS"
        IFS=','
        for spec in $HARNESS_HAT_LOCALHOST_FORWARDS; do
            host_port="${spec#*:}"
            [ "$host_port" != "$spec" ] || host_port="$spec"
            case "$host_port" in
                ''|*[!0-9]*)
                    echo "harness-hat: invalid localhost forward spec: $spec" >&2
                    exit 1
                    ;;
            esac
            $IPT -w -t filter -A HH_EGRESS -p tcp -d "$forward_ip" --dport "$host_port" -j ACCEPT
        done
        IFS="$old_ifs"
    fi
    $IPT -w -t filter -A HH_EGRESS -j REJECT 2>/dev/null || $IPT -w -t filter -A HH_EGRESS -j DROP

    # IPv6: reject everything to avoid long hangs on AAAA/QUIC attempts.
    if [ -n "$IP6T" ]; then
        $IP6T -w -t filter -N HH_EGRESS 2>/dev/null || $IP6T -w -t filter -F HH_EGRESS
        $IP6T -w -t filter -C OUTPUT -j HH_EGRESS 2>/dev/null || $IP6T -w -t filter -I OUTPUT 1 -j HH_EGRESS
        $IP6T -w -t filter -F HH_EGRESS
        $IP6T -w -t filter -A HH_EGRESS -o lo -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -o tun0 -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -j REJECT 2>/dev/null || $IP6T -w -t filter -A HH_EGRESS -j DROP
    fi

    # ── Layer 2: tun2proxy routing ───────────────────────────────────────
    # Bypass the scoped proxy and exec bridge addresses so tun2proxy can talk
    # to them directly.  Docker's DNS (127.0.0.11) remains reachable.
    TUN2PROXY_BIN="$(command -v tun2proxy-bin 2>/dev/null || true)"
    if [ -z "$TUN2PROXY_BIN" ]; then
        for candidate in \
            /usr/local/bin/tun2proxy-bin \
            /usr/local/cargo/bin/tun2proxy-bin \
            /root/.cargo/bin/tun2proxy-bin
        do
            if [ -x "$candidate" ]; then
                TUN2PROXY_BIN="$candidate"
                break
            fi
        done
    fi
    if [ -z "$TUN2PROXY_BIN" ]; then
        echo "harness-hat: tun2proxy-bin not found in PATH or common cargo locations" >&2
        exit 1
    fi
    if [ -n "$forward_ip" ]; then
        "$TUN2PROXY_BIN" \
            --setup \
            --proxy "http://harness-hat:${HARNESS_HAT_SCOPED_PROXY_AUTH}@${proxy_ip}:${proxy_port}" \
            --dns virtual \
            --bypass "$proxy_ip" \
            --bypass "$exec_ip" \
            --bypass "$forward_ip" \
            >/tmp/harness-hat-tun2proxy.log 2>&1 &
    else
        "$TUN2PROXY_BIN" \
            --setup \
            --proxy "http://harness-hat:${HARNESS_HAT_SCOPED_PROXY_AUTH}@${proxy_ip}:${proxy_port}" \
            --dns virtual \
            --bypass "$proxy_ip" \
            --bypass "$exec_ip" \
            >/tmp/harness-hat-tun2proxy.log 2>&1 &
    fi
    HH_TUN2PROXY_PID=$!
    sleep 1
    if ! kill -0 "$HH_TUN2PROXY_PID" 2>/dev/null; then
        echo "harness-hat: tun2proxy failed to start" >&2
        cat /tmp/harness-hat-tun2proxy.log >&2 || true
        exit 1
    fi

    # With TUN capture active, application-level proxy env vars are not needed
    # and can cause double-proxying in clients that partially support them.
    unset HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
    unset http_proxy https_proxy all_proxy no_proxy

    echo "harness-hat: strict_network ready (tun2proxy + iptables filter)" >&2
fi

clear 2>/dev/null || true

if [ "$(id -u)" = "0" ]; then
    exec gosu 1000:1000 "$@"
fi
exec "$@"
SCRIPT
RUN chmod 755 /usr/local/bin/harness-hat-init.sh

# ubuntu:24.04 ships with an 'ubuntu' user at uid/gid 1000.
USER ubuntu
WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/harness-hat-init.sh"]
CMD ["/bin/bash"]
